version: "3.8"
services:
  nats:
    container_name: nats-leader
    image: nats:2.10.1
    command: --cluster_name nats-instance --cluster nats://0.0.0.0:6222 --http_port 8222
    ports:
      - "4222:4222"
      - "6222:6222"
      - "8222:8222"
    networks:
      - nats
  nats-1:
    container_name: nats-cluster-1
    image: nats:2.10.1
    depends_on:
      - nats
    command: --cluster_name nats-instance --cluster nats://0.0.0.0:6222 --routes=nats://ruser:T0pS3cr3t@nats:6222
    networks:
      - nats
  nats-2:
    container_name: nats-cluster-2
    image: nats:2.10.1
    depends_on:
      - nats
    command: --cluster_name nats-instance --cluster nats://0.0.0.0:6222 --routes=nats://ruser:T0pS3cr3t@nats:6222
    networks:
      - nats
networks:
  nats:
    name: nats
